# Generated by Django 5.2.6 on 2025-09-30 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chatsession_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "strength",
                    models.TextField(
                        help_text="Student's strengths identified from the session"
                    ),
                ),
                (
                    "weakness",
                    models.TextField(help_text="Areas where student needs improvement"),
                ),
                (
                    "opportunity",
                    models.TextField(
                        help_text="Learning opportunities for the student"
                    ),
                ),
                (
                    "threat",
                    models.TextField(help_text="Potential challenges or obstacles"),
                ),
                (
                    "total_qa_pairs",
                    models.IntegerField(
                        default=0,
                        help_text="Total question-answer pairs in the session",
                    ),
                ),
                (
                    "session_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of session in minutes",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_insights",
                        to="api.document",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight",
                        to="api.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Insight",
                "verbose_name_plural": "Session Insights",
                "ordering": ["-created_at"],
            },
        ),
    ]
