# Generated by Django 5.2.6 on 2025-09-30 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_sessioninsight"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="Document this session is based on (for tutoring sessions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                to="api.document",
            ),
        ),
    ]
