# Generated by Django 5.2.6 on 2025-10-02 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_chatsession_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutoringQuestionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(help_text="Array of pre-generated questions"),
                ),
                (
                    "current_question_index",
                    models.IntegerField(
                        default=0, help_text="Index of the current question being asked"
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(
                        help_text="Total number of questions in the batch"
                    ),
                ),
                (
                    "source_doc_id",
                    models.CharField(
                        blank=True,
                        help_text="Source document ID used for generation",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tenant_tag",
                    models.CharField(
                        help_text="Tenant tag for multi-tenancy", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_batches",
                        to="api.document",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_batch",
                        to="api.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutoring Question Batch",
                "verbose_name_plural": "Tutoring Question Batches",
                "ordering": ["-created_at"],
            },
        ),
    ]
