# Generated by Django 5.2.6 on 2025-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatmessage_classifier_token_chatsession_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninsight',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Percentage accuracy (0-100) based on correct answers', null=True),
        ),
        migrations.AddField(
            model_name='sessioninsight',
            name='edge_zone',
            field=models.JSONField(blank=True, help_text='Array of 2 Tanglish points - potential improvement/growth areas', null=True),
        ),
        migrations.AddField(
            model_name='sessioninsight',
            name='focus_zone',
            field=models.JSONField(blank=True, help_text='Array of 2 Tanglish points - low understanding/weak areas', null=True),
        ),
        migrations.AddField(
            model_name='sessioninsight',
            name='steady_zone',
            field=models.JSONField(blank=True, help_text='Array of 2 Tanglish points - high clarity/strong areas', null=True),
        ),
        migrations.AddField(
            model_name='sessioninsight',
            name='xp_points',
            field=models.IntegerField(default=0, help_text='Total XP earned (1 XP per answered question)'),
        ),
        migrations.AlterField(
            model_name='sessioninsight',
            name='opportunity',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED: Use edge_zone instead'),
        ),
        migrations.AlterField(
            model_name='sessioninsight',
            name='strength',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED: Use steady_zone instead'),
        ),
        migrations.AlterField(
            model_name='sessioninsight',
            name='threat',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED: No longer used'),
        ),
        migrations.AlterField(
            model_name='sessioninsight',
            name='weakness',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED: Use focus_zone instead'),
        ),
    ]
