# Generated by Django 5.2.6 on 2025-10-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sessioninsight_accuracy_sessioninsight_edge_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('english', 'English'), ('tanglish', 'Tanglish')], default='tanglish', help_text='User preferred language for tutoring responses', max_length=32),
        ),
    ]
