# Generated by Django 5.2.6 on 2025-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sessionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorresult',
            name='progress_processed',
            field=models.BooleanField(default=False, help_text='Whether this evaluation has been processed for streak/batch progress updates'),
        ),
        migrations.AddField(
            model_name='user',
            name='batch_current',
            field=models.CharField(default='Bronze', help_text='Current batch level: Bronze, Silver, Gold, or Platinum', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='current_star',
            field=models.IntegerField(default=0, help_text='Number of stars earned in current batch (0 to stars_per_batch)'),
        ),
        migrations.AddField(
            model_name='user',
            name='stars_per_batch',
            field=models.IntegerField(default=5, help_text='Number of stars required to complete a batch and advance to next level'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_current',
            field=models.IntegerField(default=0, help_text='Current consecutive daily test streak count'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_earned_batches',
            field=models.JSONField(blank=True, default=list, help_text="List of earned streak milestone badges (e.g., ['Bronze (7)', 'Silver (15)']). Persists after streak resets."),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_last_test_date',
            field=models.DateField(blank=True, help_text='Date of last counted test for streak calculation (UTC)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_tests_taken',
            field=models.IntegerField(default=0, help_text='Total number of tests (EvaluatorResults) completed by user'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_xp_sum',
            field=models.IntegerField(default=0, help_text='Cumulative sum of all XP earned (used to calculate xp_points average)'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp_points',
            field=models.IntegerField(default=0, help_text='Average XP across all tests taken (recalculated on each test completion)'),
        ),
    ]
