# Generated by Django 5.2.6 on 2025-10-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_evaluatorresult_progress_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringquestionbatch',
            name='session_xp_avg',
            field=models.IntegerField(default=0, help_text='Stored per-session average XP (int)'),
        ),
        migrations.AddField(
            model_name='tutoringquestionbatch',
            name='xp_processed',
            field=models.BooleanField(default=False, help_text='Whether this batch/session has been processed for XP aggregation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_tests_taken',
            field=models.IntegerField(default=0, help_text='Total number of sessions/tests completed by user (used as session count)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_xp_sum',
            field=models.IntegerField(default=0, help_text='Sum of per-session average XP values (same as xp_points, kept for compatibility)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='xp_points',
            field=models.IntegerField(default=0, help_text='Sum of per-session average XP (calculated when each session completes)'),
        ),
    ]
