# Generated by Django 5.2.6 on 2025-10-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tutoringquestionbatch_session_xp_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_tests_taken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xp_points',
        ),
    ]
