# Generated by Django 5.2.6 on 2025-10-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_user_total_tests_taken_remove_user_xp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninsight',
            name='edge_zone_reasons',
            field=models.JSONField(blank=True, help_text='Array of 2 reasons explaining why edge_zone was identified', null=True),
        ),
        migrations.AddField(
            model_name='sessioninsight',
            name='focus_zone_reasons',
            field=models.JSONField(blank=True, help_text='Array of 2 reasons explaining why focus_zone was identified', null=True),
        ),
        migrations.AddField(
            model_name='sessioninsight',
            name='steady_zone_reasons',
            field=models.JSONField(blank=True, help_text='Array of 2 reasons explaining why steady_zone was identified', null=True),
        ),
    ]
