name: Build TWA Android AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 36
          target: android-36

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Prepare keystore
        run: |
          mkdir -p inzighted-twa
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > inzighted-twa/android.keystore
          cat > inzighted-twa/keystore.properties <<EOF
          storeFile=inzighted-twa/android.keystore
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Build bundle
        working-directory: inzighted-twa
        run: ./gradlew bundleRelease --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: inzighted-twa-aab
          path: inzighted-twa/app/build/outputs/bundle/release/app-release.aab

      - name: Cleanup keystore
        run: |
          shred -u inzighted-twa/android.keystore || rm -f inzighted-twa/android.keystore
          rm -f inzighted-twa/keystore.properties
*** End Patch